### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by d34vbd5** [johntitus/coinx#21]
What is wrong with my installation? I can successfully get my funds from kraken but i can't buy anything or check specific prices:

coinx price btc
/usr/local/lib/node_modules/coinx/commands/coinx-price.js:12
const exchanges = Object.values(coinx.exchanges());
                                             ^

TypeError: Object.values is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/coinx/commands/coinx-price.js:12:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by johntitus** [comment]
You may need to update your version of Node. Object values is supported in
version 7 and up.

**Comment by d34vbd5** [comment]
Thank you, i installed v6.11.1 LTS.. after updating the Node.js version i'm able to get prices but i'm still unable to do purchases. I tried to use kraken and get "Error: Kraken API returned error: Order:Trading agreement required". Any idea about that error? The Kraken API is set to allow everything.

**Comment by johntitus** [comment]
That sounds like a Kraken issue, not related to this library. Have you
manually traded coins on there? Do you have funds in the right wallet?
