### ISSUE TITLE
Error: Kraken API returned error: General:Invalid arguments:volume

### ISSUE THREAD

**Issue by tparvi** [johntitus/coinx#22]
Trying to buy either single coin or all the coins gives me that error. Note that querying works just fine. I'm on Windows (tried with git bash and normal command prompt and result is the same). I'm using the latest version.

```
tonip@JAARA MINGW64 /c/coinsim
$ coinx buy eth -$ 2
Buying...
Checking Ethereum (ETH) on the markets...
Best price found on Kraken at $293.82

*Note that the number of coins may change slightly if the market fluctuates*

? Buy about 0.00680695 worth of ETH? (Y/n) y
? Buy about 0.00680695 worth of ETH? Yes
Buying...
An error occurred.
{ Error: Kraken API returned error: General:Invalid arguments:volume
    at Request._callback (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\kraken-api\kraken.js:156:34)
    at Request.self.callback (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  cause:
   Error: Kraken API returned error: General:Invalid arguments:volume
       at Request._callback (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\kraken-api\kraken.js:156:34)
       at Request.self.callback (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\request\request.js:188:22)
       at emitTwo (events.js:125:13)
       at Request.emit (events.js:213:7)
       at Request.<anonymous> (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\request\request.js:1171:10)
       at emitOne (events.js:115:13)
       at Request.emit (events.js:210:7)
       at IncomingMessage.<anonymous> (C:\Users\tonip\AppData\Roaming\npm\node_modules\coinx\node_modules\request\request.js:1091:12)
       at Object.onceWrapper (events.js:314:30)
       at emitNone (events.js:110:20)
       at IncomingMessage.emit (events.js:207:7)
       at endReadableNT (_stream_readable.js:1045:12)
       at _combinedTickCallback (internal/process/next_tick.js:138:11)
       at process._tickCallback (internal/process/next_tick.js:180:9),
  isOperational: true }


```

**Comment by johntitus** [comment]
Ya, I've been getting that too but haven't had time to investigate. I
wonder if Kraken has changed their API?

**Comment by tparvi** [comment]
It seems to be issue on their (Kraken) end https://www.reddit.com/r/BitcoinMarkets/comments/6pvh4c/kraken_minimum_volume_issue/

Minimums https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

**Comment by amibenson** [comment]
It has been a year+ by now. 

Does anyone know if Kraken API now allows getting the minimum number of units (aka quantity) in a programmatic manner ?

i.e: list of minimums same as here - https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

**Comment by evan-coygo** [comment]
@amibenson  The `AssetPairs` REST API has an "orderMin" property now https://api.kraken.com/0/public/AssetPairs
